### ISSUE TITLE
[question] how to set locale ?

### ISSUE THREAD

**Issue by monkeydri** [birik/react-week-calendar#4]
I would like to display days in another language than English (I use `dayFormat` "dddd").

I tried to set `moment.locale('es');` to no avail. Any clue ?

**Comment by birik** [comment]
Hi

I think the problem is that the instance of firstDay property is created with default locale before you change the locale to "es". You can try to send the firstDay property with new local when you initiate the calender. It should help.

I will try to make some general solution next weekend

**Comment by monkeydri** [comment]
My bad, it actually works after importing the desired locale after importing moment :

```jsx
import moment from 'moment';
import 'moment/locale/es';

moment.locale('es');

const Calendar = () => <WeekCalendar firstDay={moment('2019-01-01')} />;
```
